### PR TITLE
Fix up the posted_content.xml template to match Crossref schema

### PR DESCRIPTION
**Pull request by hardyoyo**
* moves jats:abstract to the correct location (after the dates)
* fixes the markup of the VoR entry

### CODE REVIEW

**Comment by hardyoyo** [comment]
FYI: this code is currently running in production, and not returning errors from Crossref

**Comment by myucekul** [comment]
I have a question about posted and acceptance dates. Is it okay to use now date if any of the date fields are missing?

**Comment by hardyoyo** [comment]
@myucekul: I believe it's OK, for this plugin, where a preprint is being accepted, to assume any missing dates are "now" so that a DOI can be minted without further intervention. The metadata can be updated, and this plugin supports updates.

**Comment by hardyoyo** [comment]
Code has been running in production for more than 2 days, this should probably be merged.

**Comment by tingletech** [comment]
For calisphere, we usually try merge and deploy at the same time.  Are you waiting for a review?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
