### PR TITLE
Add validation for ORCID, surname, given_name, before sending request to EZID

### PR DESCRIPTION
**Pull request by hardyoyo**
Addressing some issues identified by @myucekul during the review of #2

### CODE REVIEW

**Comment by myucekul** [comment]
Last name is must have in the xml. So when last name is not present then use first name as surname.

**Comment by myucekul** [comment]
Looks good. Thanks for the update, Hardy. 👍 
Thankfully I haven't seen an author with both last and first name null or empty.

**Review by tingletech — APPROVED** [review]

**Comment by myucekul** [comment]
Test case - create doi for preprint with author whose last name is empty string. "" or bunch of white spaces "  ". See if crossref is okay or not.

**Comment by hardyoyo** [comment]
this PR has been merged and deployed... I don't believe we can get crossref feedback on the staging server, so we'd have to test this in prd...

**Pull request merged**
